version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1400
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
